turbolinks_verification/config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#top'
  get 'example' => 'example#index'
end

turbolinks_verification/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

turbolinks_verification/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

turbolinks_verification/app/controllers/example_controller.rb
class ExampleController < ApplicationController
  def index
  end
end

turbolinks_verification/app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

turbolinks_verification/app/helpers/application_helper.rb
module ApplicationHelper
end

turbolinks_verification/app/helpers/example_helper.rb
module ExampleHelper
end

turbolinks_verification/app/helpers/homes_helper.rb
module HomesHelper
end

turbolinks_verification/app/views/example/index.html.erb
<h1>Turbolinksの検証</h1>

turbolinks_verification/app/views/homes/top.html.erb
<h1>トップページ</h1>
<%= link_to "別ページへ", example_path %>

turbolinks_verification/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TurbolinksVerification</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://code.jquery.com/jquery-3.6.0.slim.js" integrity="sha256-HwWONEZrpuoh951cQD1ov2HUK5zA5DwJ1DNUXaM6FsY=" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>